services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=easy_check
      - POSTGRES_USER=easy_check
      - POSTGRES_PASSWORD=127238
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d easy_check -U easy_check"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  web:
    build: .
    ports:
      - 8000:8000
      - 80:80
    command: sh -c "uvicorn --host 0.0.0.0 --port 8000 app:app"
    environment:
      - DB_URL=postgresql://easy_check:127238@db:5432/easy_check
    volumes:
      - media_volume:/app/media
    healthcheck:
      test: curl --fail http://localhost:8000/docs || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      - db

volumes:
  media_volume:
  db_data: